Repository WSU-4110/Eventsly, pull requests merged in 2021-11, with the labels that each got.

#49 BUG: Logger and miscellaneous
  app.py
  static/scripts/searchEvent.js
  static/styles/bookmarksStyleSheet.css
  templates/Bookmarks.html
  templates/search.html
Labels: bug

#58 UPDATE: Create Event
  app.py
  models.py
  templates/createEvent.html
Labels: enhancement

#59 Front-end Validation
  app.py
  models.py
  static/scripts/FormValidator.js
  static/scripts/createEventMap.js
  static/scripts/formScripts.js
  static/scripts/mapScripts.js
  static/styles/bookmarksStyleSheet.css
  static/styles/createEventStyleSheet.css
  static/styles/formStyles.css
  static/styles/frostedStyleSheet.css
  static/styles/mapStyleSheet.css
  static/styles/navbarStyleSheet.css
  templates/Bookmarks.html
  templates/base.html
  templates/createEvent.html
  templates/dashboard.html
  templates/includes/_formhelpers.html
  templates/index.html
  templates/login.html
  templates/signup.html
Labels: Non-Functional
